{% set name = "nasdaq-data-link" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Nasdaq Data Link-{{ version }}.tar.gz
  sha256: 7beae38ff0b376db24a50d6b8445c94832ebdd88737f6aafbc81a7dbdda25ca1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=0.14
    - numpy >=1.8
    - requests >=2.7.0
    - inflection >=0.3.1
    - python-dateutil
    - six
    - more-itertools

test:
  imports:
    - nasdaqdatalink
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Nasdaq/data-link-python
  summary: Package for Nasdaq Data Link API access
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
